POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName": "Tsetso",
  "lastName":"Yrdanov",
  "password": "1225@:5544RRRrr!.",
  "confirmPassword" : "1225@:5544RRRrr!.",
  "email":"cvetalin@abv.bg",
  "phoneNumber": "0899999999",
  "dateOfBirth":"13.06.2018"



}


###
GET localhost:3333/users/5