POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName": "Kaloyan",
  "lastName": "Todorov",
  "password": "k12@.03Doka",
  "confirmPassword": "k12@.03Doka",
  "phoneNumber": "0988880088887",
  "email": "kalt11odo@gmail.com",
  "dateOfBirth": "2012-04-23T18:25:43.511Z"
}

###

POST localhost:3333/users/log_in
Content-Type: application/json

{
  "email": "kalt11odo@gmail.com",
  "password": "k12@.03Doka"
}

###
GET localhost:3333/users

###
GET localhost:3333/users/3

###
GET localhost:3333/categories/20

###
GET localhost:3333/videos/1

###
DELETE localhost:3333/users?id=4

###
GET localhost:3333/comments/20

###
GET localhost:3333/play_lists/1

###
POST localhost:3333/comments?vid=1
Content-Type: application/json

{
  "videoId": 1,
  "text": "test sure check",
  "creationDate": "2012-04-23T18:25:43.511Z"
}

###
POST  localhost:3333/videos/upload
Content-Type: application/json

{
  "title": "First My Video",
  "userId": 3,
  "uploadDate": "2012-04-23T18:25:43.511Z",
  "videoUrl": "wgrgrgregrere"

}
###
PUT localhost:3333/videos/like?videoId=2
Content-Type: application/json

{
  "title": "First My Video",
  "userId": 1,
  "uploadDate": "2012-04-23T18:25:43.511Z",
  "videoUrl": "wgrgrgregrere"

}