GET localhost:3333/categories/1
###
GET localhost:3333/categories
###
POST localhost:3333/categories/follow?cid=1
###
DELETE localhost:3333/categories/unfollow?cid=1
###
POST localhost:3333//categories/add_to_video?vid=3&cid=1
###
DELETE localhost:3333/categories/remove_video?vid=3&cid=1
###