GET localhost:3333/comments/5
###
POST localhost:3333/comments?vid=1
Content-Type: application/json

{
  "videoId" : 1,
  "text": "tova sa istinski macki"
}
###
PUT localhost:3333/comments
Content-Type: application/json

{
  "id": 10,
  "text": "tezi koteta sa mnogo sladki"
}
###
DELETE localhost:3333/comments?id=2
###
POST localhost:3333/comments/like?cid=7
###
POST localhost:3333/comments/dislike?cid=7
###
DELETE  localhost:3333/comments/remove_reaction?cid=7
###
POST localhost:3333/comments/respond?cid=13
Content-Type: application/json

{
  "text": "sam si komentiram komentara"
}