GET localhost:3333/comments/5
###
POST localhost:3333/comments?vid=1
Content-Type: application/json

{
  "videoId" : 1,
  "text": "ah tezi koteta"
}
###
PUT localhost:3333/comments
Content-Type: application/json

{
  "id": 10,
  "text": "tezi koteta sa mnogo sladki"
}
###
DELETE localhost:3333/comments?id=2
###
POST localhost:3333/comments/like?cid=7
###
POST localhost:3333/comments/dislike?cid=5
###
DELETE  localhost:3333/comments/remove_reaction?cid=7
###
POST localhost:3333/comments/respond?cid=11
Content-Type: application/json

{
  "text": "strahotni sa nali"
}