POST localhost:3333/playlist/create
Content-Type: application/json

{
"title" : "Tretiq playlist  bace",
"isPrivate" : 1
}
###
GET localhost:3333/playlist/3
###
DELETE localhost:3333/playlist/delete?plId=4
###
POST localhost:3333/playlist
###
POST localhost:3333/playlist
###
DELETE localhost:3333/playlist/delete_video?vId=8&plid=3
###
POST localhost:3333/playlist/add_video?vId=8&plId=3