POST localhost:3333/playlists/upload_background_image?plId=5
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="background_image"; filename="download.jpg"

< /Users/Admin/Desktop/ZoomBackground/download.jpg
--WebAppBoundary--
###

POST localhost:3333/playlists/create
Content-Type: application/json

{
"title" : "Tretiq playlist grande",
"isPrivate" : true
}
###
GET localhost:3333/playlists/3
###
DELETE localhost:3333/playlists/delete?plId=1
###
DELETE localhost:3333/playlists/delete_video?vId=8&plid=3
###
POST localhost:3333/playlists/add_video?vId=5&plId=3
###
GET localhost:3333/playlists?title=bace

