POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName" : "Kiril",
  "lastName" : "Efremov",
  "password" : "po01.?@dA",
  "confirmPassword" : "po01.?@dA",
  "phoneNumber" : "0888888982388252",
  "email": "baceeeeeee@gmail.com",
  "dateOfBirth" : "2010-02-22T18:25:43.511Z"
}

###
POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName" : "Kaloyan",
  "lastName" : "Todorov",
  "password" : "k1@.0653Doka",
  "confirmPassword" : "k1@.0653Doka",
  "phoneNumber" : "088843882222888",
  "email": "kaltodor11@gmail.com",
  "dateOfBirth" : "2010-02-22T18:25:43.511Z"
}

###
POST localhost:3333/users/log_in
Content-Type: application/json

{
  "email": "baceeeeeee@gmail.com",
  "password" : "po01.?@dA"

}
###
POST localhost:3333/users/log_in
Content-Type: application/json

{
"email": "kaltodor11@gmail.com",
"password" : "k1@.0653Doka"
}

###
GET localhost:3333/users
###
GET localhost:3333/users/18
###
POST localhost:3333/users/follow?publisherId=3
###
POST localhost:3333/users/unfollow?publisherId=3
###
DELETE localhost:3333/users?id=21
###
POST localhost:3333/users/logout
###
GET localhost:3333/users/search?name=r
###
PUT localhost:3333/users/reset_password
Content-Type: application/json

{
  "oldPass": "po01.?@dA",
  "newPass": "po01.?@dQ",
  "confirmPass": "po01.?@dQ"
}
###
PUT localhost:3333/users/forgotten_password?email=baceeeeee@gmail.com
###
PUT localhost:3333/users/verify_registration/1645544983224$$$99651*=3214@33@1645544983224

