POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName" : "Kaloyan",
  "lastName" : "Todorov",
  "password" : "k1@.063Doka",
  "confirmPassword" : "k1@.063Doka",
  "phoneNumber" : "0888888988852",
  "email": "kaltodo11111@abv.bg",
  "dateOfBirth" : "2010-04-23T18:25:43.511Z"
}

###
POST localhost:3333/users/register
Content-Type: application/json

{
  "firstName" : "Kaloyan",
  "lastName" : "Todorov",
  "password" : "k1@.0653Doka",
  "confirmPassword" : "k1@.0653Doka",
  "phoneNumber" : "088888880",
  "email": "kaltodo15@abv.bg",
  "dateOfBirth" : "2010-04-23T18:25:43.511Z"
}

###
POST localhost:3333/users/log_in
Content-Type: application/json

{
  "email": "kaltodo15@abv.bg",
  "password" : "k1@.0653Doka"
}
###
POST localhost:3333/users/log_in
Content-Type: application/json

{
"email": "kaltodo15@abv.bg",
"password" : "k1@.0653Doka"
}

###
GET localhost:3333/users
###
GET localhost:3333/users/10
###
POST localhost:3333/users/follow?publisherId=10
###
POST localhost:3333/users/unfollow?publisherId=3
###
DELETE localhost:3333/users?id=4
###
POST localhost:3333/user/logout
###
GET localhost:3333/users/search?name=lo