POST http://localhost:3333/videos/upload_image?vId=4
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="241633633_140067204923629_5571897423002582296_n (2).jpg"

< /Users/Admin/Desktop/ZoomBackground/241633633_140067204923629_5571897423002582296_n (2).jpg
--WebAppBoundary--

###
POST localhost:3333/videos/upload
Content-Type: application/json

{
  "title": "kotkite sa 1ki",
  "uploadDate" : "2010-04-23T18:25:43.511Z",
  "videoUrl": "asddfsdg",
  "isPrivate" :  true
}
###
GET localhost:3333/videos/2
###
PUT localhost:3333/videos/like?vId=7
###
PUT localhost:3333/videos/dislike?vId=7
###
DELETE localhost:3333/videos/remove_reaction?vId=7
###
POST localhost:3333/videos/watch?vId=7
###
GET localhost:3333/videos/search_by_title?title=kotk
###
GET localhost:3333/videos/order_by_watched?validator=desc
###
GET localhost:3333/videos/order_by_upload_date?validator=desc
###
GET localhost:3333/videos/get_all?pageNumber=0&rowNumbers=12
###
PUT localhost:3333/videos/upload/dropbox?vId=9