POST localhost:3333/videos/upload
Content-Type: application/json

{
    "title": "kotki",
  "video_url": "asddfsdg"
}
###
PUT localhost:3333/videos/like?vId=1
###
PUT localhost:3333/videos/dislike?vId=1
###
DELETE localhost:3333/videos/remove_reaction?vId=1
###
POST localhost:3333/videos/1/watch
###
POST localhost:3333/videos/add_to_playlist?vId=1&plId=1